// @generated — DO NOT EDIT MANUALLY
// Last synced: 2026-03-30 05:06:17 UTC
// Source: Figma "Supernova Design System"
// Run: yarn workspace @keplr-wallet/design-system sync:tokens

/**
 * Unified Design System colors.
 * Primitive: DSColor.blue400, DSColor.gray10
 * Semantic:  DSColor.typography.primary, DSColor.fill.neutral.high
 */
export const DSColor = {
  // ── Primitives ──
  black: "#000000",

  blue200: "#78D9FF",
  blue300: "#35C6FF",
  blue400: "#14AFEB",
  blue400_10: "rgba(20, 175, 235, 0.1)",
  blue400_15: "rgba(20, 175, 235, 0.15)",
  blue400_25: "rgba(20, 175, 235, 0.25)",
  blue400_50: "rgba(20, 175, 235, 0.5)",
  blue500: "#009FDD",
  blue600: "#0093CC",
  blue700: "#00719C",
  blue800: "#21262D",

  gray10: "#F6F6F9",
  gray10_3: "rgba(246, 246, 249, 0.03)",
  gray10_5: "rgba(246, 246, 249, 0.05)",
  gray10_7: "rgba(246, 246, 249, 0.07)",
  gray10_10: "rgba(246, 246, 249, 0.1)",
  gray10_15: "rgba(246, 246, 249, 0.15)",
  gray10_50: "rgba(246, 246, 249, 0.5)",
  gray200: "#ABABB5",
  gray300: "#72747B",
  gray400: "#424247",
  gray500: "#2E2E32",
  gray550: "#242428",
  gray600: "#1D1D1F",
  gray650: "#151517",
  gray700: "#09090A",
  gray700_5: "rgba(9, 9, 10, 0.05)",
  gray700_7: "rgba(9, 9, 10, 0.07)",
  gray700_50: "rgba(9, 9, 10, 0.5)",
  gray700_60: "rgba(9, 9, 10, 0.6)",
  gray700_80: "rgba(9, 9, 10, 0.8)",

  green100: "#DBF9EC",
  green200: "#AAECD0",
  green400: "#2DD98F",
  green500: "#22AC71",
  green600: "#18925E",
  green600_10: "rgba(24, 146, 94, 0.1)",
  green600_20: "rgba(24, 146, 94, 0.2)",
  green600_50: "rgba(24, 146, 94, 0.5)",
  green600_80: "rgba(24, 146, 94, 0.8)",
  green800: "#0D2F21",

  orange100: "#FFE3D3",
  orange200: "#FFAD80",
  orange400: "#FA6410",
  orange400_10: "rgba(250, 100, 16, 0.1)",
  orange400_25: "rgba(250, 100, 16, 0.25)",
  orange400_35: "rgba(250, 100, 16, 0.35)",
  orange400_50: "rgba(250, 100, 16, 0.5)",
  orange500: "#D7560E",
  orange600: "#8F3A0A",
  orange800: "#2D1609",

  purple300: "#A095FF",
  purple400: "#7B6BFF",

  white: "#FFFFFF",

  yellow200: "#EDD18A",
  yellow400: "#F0B622",
  yellow400_10: "rgba(240, 182, 34, 0.1)",
  yellow400_25: "rgba(240, 182, 34, 0.25)",
  yellow600: "#A67B0C",
  yellow800: "#2F2611",

  transparent: "rgba(255, 255, 255, 0)",

  // ── Semantic (CSS variable refs) ──
  fill: {
    accent: {
      purple: "var(--ds-fill-accent-purple)" as const,
    },
    neutral: {
      high: "var(--ds-fill-neutral-high)" as const,
      strong: "var(--ds-fill-neutral-strong)" as const,
      medium: "var(--ds-fill-neutral-medium)" as const,
      low: "var(--ds-fill-neutral-low)" as const,
      high_7: "var(--ds-fill-neutral-alpha-high-7)" as const,
      high_10: "var(--ds-fill-neutral-alpha-high-10)" as const,
      high_50: "var(--ds-fill-neutral-alpha-high-50)" as const,
    },
    alert: {
      medium: "var(--ds-fill-alert-medium)" as const,
      medium_10: "var(--ds-fill-alert-alpha-medium-10)" as const,
      medium_25: "var(--ds-fill-alert-alpha-medium-25)" as const,
      medium_50: "var(--ds-fill-alert-alpha-medium-50)" as const,
    },
    positive: {
      high: "var(--ds-fill-positive-high)" as const,
      strong: "var(--ds-fill-positive-strong)" as const,
      medium: "var(--ds-fill-positive-medium)" as const,
      low: "var(--ds-fill-positive-low)" as const,
    },
    brand: {
      high: "var(--ds-fill-brand-high)" as const,
      strong: "var(--ds-fill-brand-strong)" as const,
      medium: "var(--ds-fill-brand-medium)" as const,
      low: "var(--ds-fill-brand-low)" as const,
    },
    warning: {
      medium: "var(--ds-fill-warning-medium)" as const,
      medium_10: "var(--ds-fill-warning-alpha-medium-10)" as const,
    },
  },
  background: {
    surface: {
      elevated: "var(--ds-background-surface-elevated)" as const,
      surface: "var(--ds-background-surface-surface)" as const,
      scrim: "var(--ds-background-surface-scrim)" as const,
      ground: "var(--ds-background-surface-ground)" as const,
    },
  },
  stroke: {
    separator: {
      primary: "var(--ds-stroke-separator-primary)" as const,
      secondary: "var(--ds-stroke-separator-transparent-→-secondary)" as const,
    },
    input: {
      error: "var(--ds-stroke-input-error)" as const,
      default: "var(--ds-stroke-input-default)" as const,
      strong: "var(--ds-stroke-input-strong)" as const,
    },
  },
  typography: {
    brand: "var(--ds-typography-brand)" as const,
    primary: "var(--ds-typography-primary)" as const,
    inverted: "var(--ds-typography-inverted)" as const,
    secondary: "var(--ds-typography-secondary)" as const,
    tertiary: "var(--ds-typography-tertiary)" as const,
    disabled: "var(--ds-typography-disabled)" as const,
    warning: {
      light: "var(--ds-typography-warning-light)" as const,
      medium: "var(--ds-typography-warning-medium)" as const,
      strong: "var(--ds-typography-warning-strong)" as const,
    },
    accent: {
      purple: "var(--ds-typography-accent-purple)" as const,
    },
    alert: {
      light: "var(--ds-typography-alert-light)" as const,
      medium: "var(--ds-typography-alert-medium)" as const,
      strong: "var(--ds-typography-alert-strong)" as const,
    },
    positive: {
      light: "var(--ds-typography-positive-light)" as const,
      medium: "var(--ds-typography-positive-medium)" as const,
      strong: "var(--ds-typography-positive-strong)" as const,
    },
  },
  form: {
    input: {
      placeholder: "var(--ds-form-input-placeholder)" as const,
    },
  },
  button: {
    primary: "var(--ds-button-primary)" as const,
    alert: "var(--ds-button-alert)" as const,
    warning: "var(--ds-button-warning)" as const,
    primaryTransparent: "var(--ds-button-primary-transparent)" as const,
    secondary: "var(--ds-button-secondary)" as const,
    disabled: "var(--ds-button-disabled)" as const,
    primaryDisabled: "var(--ds-button-primary-disabled)" as const,
    primaryTransparentDisabled:
      "var(--ds-button-primary-transparent-disabled)" as const,
  },
} as const;

/** Dark theme CSS variable values */
export const darkThemeValues: Record<string, string> = {
  "--ds-fill-accent-purple": DSColor.purple400,
  "--ds-fill-neutral-high": DSColor.gray10,
  "--ds-fill-neutral-strong": DSColor.gray200,
  "--ds-fill-neutral-medium": DSColor.gray400,
  "--ds-fill-neutral-low": DSColor.gray600,
  "--ds-fill-neutral-alpha-high-7": DSColor.gray10_7,
  "--ds-fill-neutral-alpha-high-10": DSColor.gray10_10,
  "--ds-fill-neutral-alpha-high-50": DSColor.gray10_50,
  "--ds-fill-alert-medium": DSColor.orange400,
  "--ds-fill-alert-alpha-medium-10": DSColor.orange400_10,
  "--ds-fill-alert-alpha-medium-25": DSColor.orange400_25,
  "--ds-fill-alert-alpha-medium-50": DSColor.orange400_50,
  "--ds-fill-positive-high": DSColor.green200,
  "--ds-fill-positive-strong": DSColor.green400,
  "--ds-fill-brand-high": DSColor.blue200,
  "--ds-fill-positive-medium": DSColor.green500,
  "--ds-fill-brand-strong": DSColor.blue400,
  "--ds-fill-brand-medium": DSColor.blue600,
  "--ds-fill-brand-low": DSColor.blue800,
  "--ds-fill-positive-low": DSColor.green800,
  "--ds-background-surface-elevated": DSColor.gray600,
  "--ds-stroke-separator-primary": DSColor.gray10_15,
  "--ds-background-surface-surface": DSColor.gray650,
  "--ds-background-surface-scrim": DSColor.gray700_60,
  "--ds-background-surface-ground": DSColor.gray700,
  "--ds-stroke-separator-transparent-→-secondary": DSColor.gray10_7,
  "--ds-typography-brand": DSColor.blue300,
  "--ds-typography-primary": DSColor.gray10,
  "--ds-typography-inverted": DSColor.gray650,
  "--ds-typography-secondary": DSColor.gray200,
  "--ds-typography-tertiary": DSColor.gray300,
  "--ds-typography-disabled": DSColor.gray300,
  "--ds-typography-warning-light": DSColor.yellow200,
  "--ds-typography-accent-purple": DSColor.purple300,
  "--ds-typography-warning-medium": DSColor.yellow400,
  "--ds-typography-warning-strong": DSColor.yellow800,
  "--ds-typography-alert-light": DSColor.orange100,
  "--ds-typography-alert-medium": DSColor.orange400,
  "--ds-typography-alert-strong": DSColor.orange800,
  "--ds-typography-positive-light": DSColor.green100,
  "--ds-typography-positive-medium": DSColor.green500,
  "--ds-typography-positive-strong": DSColor.green800,
  "--ds-form-input-placeholder": DSColor.gray300,
  "--ds-button-primary": DSColor.blue400,
  "--ds-button-alert": DSColor.orange400,
  "--ds-button-warning": DSColor.yellow400,
  "--ds-button-primary-transparent": DSColor.blue400_15,
  "--ds-button-secondary": DSColor.gray500,
  "--ds-button-disabled": DSColor.gray550,
  "--ds-button-primary-disabled": DSColor.blue700,
  "--ds-button-primary-transparent-disabled": DSColor.blue400_10,
  "--ds-stroke-input-error": DSColor.yellow400,
  "--ds-stroke-input-default": DSColor.gray10_15,
  "--ds-stroke-input-strong": DSColor.gray10_50,
  "--ds-fill-warning-medium": DSColor.yellow400,
  "--ds-fill-warning-alpha-medium-10": DSColor.yellow400_10,
};

/** Light theme CSS variable values */
export const lightThemeValues: Record<string, string> = {
  "--ds-fill-accent-purple": DSColor.purple400,
  "--ds-fill-neutral-high": DSColor.gray600,
  "--ds-fill-neutral-strong": DSColor.gray300,
  "--ds-fill-neutral-medium": DSColor.gray200,
  "--ds-fill-neutral-low": DSColor.gray10,
  "--ds-fill-neutral-alpha-high-7": DSColor.gray10_7,
  "--ds-fill-neutral-alpha-high-10": DSColor.gray700_7,
  "--ds-fill-neutral-alpha-high-50": DSColor.gray10_50,
  "--ds-fill-alert-medium": DSColor.orange100,
  "--ds-fill-alert-alpha-medium-10": DSColor.orange400_10,
  "--ds-fill-alert-alpha-medium-25": DSColor.orange400_25,
  "--ds-fill-alert-alpha-medium-50": DSColor.orange400_50,
  "--ds-fill-positive-high": DSColor.green800,
  "--ds-fill-positive-strong": DSColor.green500,
  "--ds-fill-brand-high": DSColor.blue800,
  "--ds-fill-positive-medium": DSColor.green400,
  "--ds-fill-brand-strong": DSColor.blue400,
  "--ds-fill-brand-medium": DSColor.blue600,
  "--ds-fill-brand-low": DSColor.blue200,
  "--ds-fill-positive-low": DSColor.green200,
  "--ds-background-surface-elevated": DSColor.gray600,
  "--ds-stroke-separator-primary": DSColor.gray10_15,
  "--ds-background-surface-surface": DSColor.gray650,
  "--ds-background-surface-scrim": DSColor.gray700_80,
  "--ds-background-surface-ground": DSColor.gray10,
  "--ds-stroke-separator-transparent-→-secondary": DSColor.gray10_7,
  "--ds-typography-brand": DSColor.blue300,
  "--ds-typography-primary": DSColor.gray600,
  "--ds-typography-inverted": DSColor.gray10,
  "--ds-typography-secondary": DSColor.gray200,
  "--ds-typography-tertiary": DSColor.gray300,
  "--ds-typography-disabled": DSColor.gray300,
  "--ds-typography-warning-light": DSColor.yellow200,
  "--ds-typography-accent-purple": DSColor.purple300,
  "--ds-typography-warning-medium": DSColor.yellow400,
  "--ds-typography-warning-strong": DSColor.yellow600,
  "--ds-typography-alert-light": DSColor.orange100,
  "--ds-typography-alert-medium": DSColor.orange400,
  "--ds-typography-alert-strong": DSColor.orange400,
  "--ds-typography-positive-light": DSColor.green400,
  "--ds-typography-positive-medium": DSColor.green400,
  "--ds-typography-positive-strong": DSColor.green400,
  "--ds-form-input-placeholder": DSColor.gray300,
  "--ds-button-primary": DSColor.blue400,
  "--ds-button-alert": DSColor.orange400,
  "--ds-button-warning": DSColor.yellow400,
  "--ds-button-primary-transparent": DSColor.blue400_15,
  "--ds-button-secondary": DSColor.gray500,
  "--ds-button-disabled": DSColor.gray550,
  "--ds-button-primary-disabled": DSColor.blue700,
  "--ds-button-primary-transparent-disabled": DSColor.blue400_10,
  "--ds-stroke-input-error": DSColor.yellow400,
  "--ds-stroke-input-default": DSColor.gray10_15,
  "--ds-stroke-input-strong": DSColor.gray10_50,
  "--ds-fill-warning-medium": DSColor.yellow200,
  "--ds-fill-warning-alpha-medium-10": DSColor.yellow400_10,
};
